# Numpy Part-1

In [1]:
import numpy as np

### 1. Numpy 배열(N-Dimensional Array)

In [2]:
a = np.array([1,3,4,7], float)
a

array([1., 3., 4., 7.])

In [3]:
a.dtype, a.shape, a.ndim, a.size
# 컴퓨터에서 기본적으로 다루는 실수데이터는 64비트(Duble Precision)
# +32비트는 Single Precisin


(dtype('float64'), (4,), 1, 4)

- Vector(1차원)

In [4]:
a = np.array([1,3,4,7], float)

- Matrix(2차원)

In [5]:
b = np.array([[1,2,4],[4,3,9],[3,7,8]])
b

array([[1, 2, 4],
       [4, 3, 9],
       [3, 7, 8]])

In [6]:
b.dtype, b.shape, b.ndim, b.size
# 정수형(int)은 32비트가 기본

(dtype('int32'), (3, 3), 2, 9)

- Tensor(3차원)

In [7]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [8]:
c.dtype, c.shape, c.ndim, c.size

(dtype('int32'), (2, 3, 4), 3, 24)

In [9]:
# dtype
np.array([1,2,3,4], dtype=np.uint8)

array([1, 2, 3, 4], dtype=uint8)

In [10]:
c.reshape(4,6) # size가 같으면 reshape 가능

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
c.reshape(3,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [12]:
c.reshape(3,-1,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [13]:
a.reshape(4, -1), a.reshape(2,2), a.reshape(-1,4)
# reshape(행, 집합수, 열)

(array([[1.],
        [3.],
        [4.],
        [7.]]),
 array([[1., 3.],
        [4., 7.]]),
 array([[1., 3., 4., 7.]]))

In [14]:
b.reshape(-1,)
# reshape은 튜플이라 원칙적으로는 원소 하나만 있을 때 콤마를 붙여야 하지만 현재 붙이지 않아도 작동함.

array([1, 2, 4, 4, 3, 9, 3, 7, 8])

In [15]:
b.flatten()

array([1, 2, 4, 4, 3, 9, 3, 7, 8])

### 2. Indexing and Sliching

In [16]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a[1][1], a[1,1], a[-1, -2]
# 인덱스로 원소 값을 호출할 때 넘파이에서는 a[행 인덱스, 열 인덱스] 형식도 가능.

(5, 5, 5)

In [18]:
a[1, :2] # 슬라이싱하기. a[행 인덱스, 열 인덱스]

array([4, 5])

In [19]:
a[:, 1:] # 슬라이싱 재밌다

array([[2, 3],
       [5, 6]])

In [20]:
b

array([[1, 2, 4],
       [4, 3, 9],
       [3, 7, 8]])

In [21]:
b[:2, 1:]

array([[2, 4],
       [3, 9]])

In [22]:
b[1:, :2]

array([[4, 3],
       [3, 7]])

In [23]:
b[:2, ::2]

array([[1, 4],
       [4, 9]])

In [24]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [25]:
c[0, 1, 1]

5

In [26]:
c[0, 1, 1:-1]

array([5, 6])

In [27]:
c[1, 1:, ::3]

array([[16, 19],
       [20, 23]])

### 3. 배열 생성

In [28]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [29]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [30]:
np.arange(1, 4.1, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [31]:
l = np.arange(1, 4.1, 0.5).tolist()
# 파이썬 자체는 정수로만 생성이 가능하기 때문에 위와 같은 방법 사용

In [32]:
np.arange(-2, 2.01, 0.02).size

201

In [33]:
# linear space를 사용하여 위와 같은 리스트 작성
np.linspace(-2, 2, 201).size
# -2에서 2전까지 201개의 원소를 가지는 리스트를 만들어서 원소 수가 몇인지 알려달라

201

- ones, zeros, empty

In [35]:
np.ones(shape=(10,), dtype=np.int16)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [37]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
np.zeros(4)

array([0., 0., 0., 0.])

In [40]:
np.empty(4) # ones와 zeros는 1 또는 0으로 배열을 초기화하는데 empty는 배열을 만들기만 하고 특정한 값으로 초기화하지 않는다.

array([0., 0., 0., 0.])

- 대각선: identity, eye

In [42]:
# A * I = A, 여기서 I를 identity, 형태는 정방형(n x n)
np.identity(3, dtype=np.int16)


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

In [43]:
# 직사각형 모양(n x m)
np.eye(N=3, M=5, dtype=np.int16)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int16)

In [47]:
np.eye(3, 5, k=1, dtype=np.int8)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=int8)

In [48]:
np.eye(3, 5, 1, dtype=np.int8)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=int8)

In [49]:
np.eye(3, 5, -1, dtype=np.int8)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]], dtype=int8)

- 데이터 분포에 따른 random sampling

In [50]:
np.random.seed(2021)

In [51]:
np.random.random(4)

array([0.60597828, 0.73336936, 0.13894716, 0.31267308])

- 정규분포와 표준편차, 분산 찾아보기. 표준 정규분포. 통계 기본 용어

In [52]:
np.random.normal(10, 4, 4)

array([12.22350333,  7.17798285, 14.52343305, 12.58000735])

In [55]:
np.random.randn(4) # 표준 정규 분포 np.random.normal(0, 1, 4)

array([-1.40232506, -0.22508127, -1.33620597,  0.30372151])

In [56]:
# 균등분포(Uniform) 분포
np.random.uniform(3, 4, 4) # 3에서 4까지의 데이터 중 4개를 

array([3.58370402, 3.47631347, 3.5178144 , 3.82309863])

In [ ]:
# 이항분포 p(1-q)