# Numpy - Part 2

In [3]:
import numpy as np

### 4. Operation

In [4]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- sum 및 axis

In [5]:
a.sum()

78

In [6]:
a.sum(axis=0)

array([15, 18, 21, 24])

In [7]:
a.sum(axis=1)

array([10, 26, 42])

In [8]:
np.sum(a[0]), np.sum(a[1:2]), np.sum(a[2:])

(10, 26, 42)

In [9]:
b = np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
np.sort(b) # axis 1, ascending order 오름차순이 기본형.

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [10]:
b.sort()

In [11]:
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [12]:
np.sort(b, axis=0)

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [13]:
c = np.array([42, 38, 12, 25])
np.sort(c)[::-1] # 내림차순으로 정렬하기

array([42, 38, 25, 12])

In [14]:
np.argsort(c) # c = np.array([42, 38, 12, 25])의 

array([2, 3, 1, 0], dtype=int64)

In [15]:
indices = np.argsort(c)
c[indices]

array([12, 25, 38, 42])

In [16]:
c[[2,3,1,0]]

array([12, 25, 38, 42])

- Mathematical functions

In [17]:
def sigmoid(x):
    return 1. / (1+ np.exp(-x
))

In [18]:
xs = np.array([-10,0,10])
sigmoid(xs)

array([4.53978687e-05, 5.00000000e-01, 9.99954602e-01])

- Transpose

In [19]:
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [20]:
b.T

array([[ 3,  1,  1],
       [ 4,  9,  2],
       [ 5, 11,  5],
       [ 7, 12, 14]])

- concatenate, vstack, hshstack

In [21]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [22]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [23]:
b = np.array([[5, 6]])
b

array([[5, 6]])

In [24]:
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
np.hstack((a, b.T))

array([[1, 2, 5],
       [3, 4, 6]])

- Array operation

In [26]:
a + a

array([[2, 4],
       [6, 8]])

In [27]:
a - a

array([[0, 0],
       [0, 0]])

In [28]:
a / a

array([[1., 1.],
       [1., 1.]])

- broadcasting

In [29]:
a + 3

array([[4, 5],
       [6, 7]])

In [30]:
a

array([[1, 2],
       [3, 4]])

- dot product

In [34]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(1,13).reshape(3,4)
a, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

In [33]:
np.dot(a,b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

In [36]:
a.dot(b) # 열과 행이 같아야 적용 가능함

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

### 5. Comparison

- All & Any

In [38]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.any(a>5), np.all(a>5)

(True, False)

In [41]:
b = np.logical_and(a > 3, a < 7)
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [42]:
np.logical_or(a < 3, a > 7)

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

- argmax, argmin

In [43]:
np.argmax(a), np.argmin(a)

(9, 0)

### 6. Boolean & Fancy index

In [44]:
a[a > 5]

array([6, 7, 8, 9])

In [45]:
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [46]:
a[b]

array([4, 5, 6])

In [47]:
a[np.logical_or(a < 3, a > 7)]


array([0, 1, 2, 8, 9])

In [48]:
a[[3,5,7]]

array([3, 5, 7])

### 7. 기술 통계

In [49]:
a = np.random.randn(10)
a

array([-0.0070447 , -0.68787846, -0.95212174, -0.44061571,  0.88159744,
       -1.70950399, -1.31817288,  1.17598029,  0.72196176,  2.78565899])

In [50]:
# 평균(mean)
a.mean(), np.mean(a)

(0.044986099942830426, 0.044986099942830426)

In [51]:
# 표준 편차(Standard deviation)
a.std(), np.std(a)

(1.2905393862421248, 1.2905393862421248)

In [52]:
# 최대값 최소값
a.max(), a.min()

(2.785658993411355, -1.7095039922876265)

In [53]:
# 4분위수
np.percentile(a, 0)

-1.7095039922876265

In [54]:
np.percentile(a, 25), np.percentile(a, 75)

(-0.8860609186447659, 0.841688519801363)

In [55]:
np.percentile(a, 50), np.median(a)

(-0.22383020501939035, -0.22383020501939035)

In [56]:
# 집단의 크기
b = np.random.randn(1000)
c = np.random.randn(100000)

In [57]:
b.mean(), c.mean()

(-0.019854808311384715, 0.0002986627340299594)

In [58]:
b.std(), c.std()

(0.992868452620408, 1.0026669504183698)