# 2021/11/26 Numpy Quiz

In [1]:
import numpy as np

### 1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오.
##### 10 20 30 40
##### 50 60 70 80

In [5]:
a = np.arange(10,81,10)
a.reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [34]:
np.arange(10,81,10).reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 2. 다음 행렬과 같은 행렬이 있다.
- m = np.array([[ 0,  1,  2,  3,  4],
- [ 5,  6,  7,  8,  9],
- [10, 11, 12, 13, 14]])
#### 1)이    행렬에서    값    7 을    인덱싱한다.
#### 2) 이    행렬에서    값    14 을    인덱싱한다.
#### 3) 이    행렬에서    배열   [6, 7] 을    슬라이싱한다.
#### 4) 이    행렬에서    배열   [7, 12] 을    슬라이싱한다.
#### 5) 이    행렬에서    배열   [[3, 4], [8, 9]] 을    슬라이싱한다.

In [8]:
l = np.arange(15)
m = l.reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
m = np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
# 1) 값 7을 인덱싱
m[1,2]

7

In [14]:
# 2) 값 14를 인덱싱
m[2,4]

# 처음에 m[2,5]로 써서 인덱스 에러 발생. 0부터 시작함.

14

In [30]:
# 3) 배열 [6,7]을 슬라이싱
m[1, 1:3]

# 처음 m[1,1:2] 로 써서 6만 자름. 끝 숫자 포함 안 됨.

array([6, 7])

In [25]:
# 4) 배열 [7,12]을 슬라이싱
# m[1:, 2:3]
m[1:,2]

# 숫자 천천히 세기.

array([ 7, 12])

In [27]:
# 5) 배열 [[3,4],[8,9]]을 슬라이싱
m[:2, 3:]

array([[3, 4],
       [8, 9]])

### 3. 2번의    행렬    m을    1차원    벡터    f 로    변환한    후    다음의    문제를    푸시오.
#### 1) 이    배열에서    3의    배수를    찾아라.
#### 2) 이    배열에서    4로    나누면    1이    남는    수를    찾아라.
#### 3) 이    배열에서    3으로   나누면    나누어지고    4로    나누면    1이    남는    수를    찾아라.

In [36]:
f = m.reshape(15)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
# 3의 배수 찾기
g = []
for i in range(len(f)):
    if i != 0:
        if i % 3 == 0:    
            g.append(i)
print(g)

[3, 6, 9, 12]


In [47]:
g = [i for i in range(len(f)) if i !=0 if i % 3 == 0]
g

[3, 6, 9, 12]

In [49]:
# 1) 배열 안에서 3의 배수 찾기
g = [i for i in f if i != 0 if i % 3 == 0]
g

[3, 6, 9, 12]

In [51]:
# 2) 배열에서 4로 나누어 1이 남는 수 찾기
g = [i for i in f if i % 4 == 1]
g

[1, 5, 9, 13]

In [53]:
# 3) 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수 찾기
g = [i for i in f if i % 3 == 0 and i % 4 == 1]
g

[9]

### 4. 값을 직접 입력하지 말고 우측의 행렬을 만드시오.
- 2, 1, 0, 0, 0
- 3, 2, 1, 0, 0
- 0, 3, 2, 1, 0
- 0, 0, 3, 2, 1
- 0, 0, 0, 3, 2

In [57]:
# 1. eye로 5 x 5 행렬 6개 만들어서 다 더하기
a = np.eye(5, k=1, dtype=int)
b = np.eye(5, dtype=int)
c = np.eye(5, dtype=int)
d = np.eye(5, k=-1, dtype=int)
e = np.eye(5, k=-1, dtype=int)
f = np.eye(5, k=-1, dtype=int)
print(a + b + c + d + e + f)

[[2 1 0 0 0]
 [3 2 1 0 0]
 [0 3 2 1 0]
 [0 0 3 2 1]
 [0 0 0 3 2]]


In [60]:
a = (np.eye(5, k=1, dtype=int))+(np.eye(5, dtype=int))+(np.eye(5, dtype=int))+(np.eye(5, k=-1, dtype=int))+np.eye(5, k=-1, dtype=int)+(np.eye(5, k=-1, dtype=int))
a

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

In [61]:
a = (np.eye(5, k=1, dtype=int))+(np.eye(5, dtype=int))*2+(np.eye(5, k=-1, dtype=int))*3
a

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

### 5. 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 들고 이 데이터에 대해 다음과 같은 값을 구하시오.
#### 1) 전체의 최댓값
#### 2) 각 행의 합
#### 3) 각 행의 최댓값
#### 4) 각 열의 평균
#### 5) 각 열의 최솟값

In [96]:
# 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 행렬
a = np.random.rand(5, 6).round(3) * 10
a

# 길어서 소수점 둘째자리까지 자름

array([[0.98, 3.25, 0.08, 2.52, 6.03, 8.86],
       [0.57, 3.88, 5.65, 8.31, 0.4 , 2.94],
       [5.27, 2.  , 4.69, 3.11, 1.26, 9.51],
       [0.82, 6.36, 7.93, 7.85, 0.65, 2.85],
       [2.42, 2.27, 5.73, 2.6 , 3.18, 4.96]])

In [97]:
# 1) 전체의 최댓값
np.max(a)


9.51

In [98]:
# 2) 각 행의 합
a.sum(axis=1)

array([21.72, 21.75, 25.84, 26.46, 21.16])

In [99]:
# 3) 각 행의 최댓값
np.max(a, axis=1)

array([8.86, 8.31, 9.51, 7.93, 5.73])

In [102]:
# 4) 각 열의 평균
a.mean(axis=0)

array([2.012, 3.552, 4.816, 4.878, 2.304, 5.824])

In [103]:
# 5) 각 열의 최솟값
np.min(a, axis=0)

array([0.57, 2.  , 0.08, 2.52, 0.4 , 2.85])

### 6. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오.
- array([[  1,    2,    3,    4],
- [ 46,   99,  100,   71],
- [ 81,   59,   90,  100]])

In [128]:
a = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
a

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [129]:
# 영어 성적 행을 재정렬
b = np.sort(a[1])
b

array([ 46,  71,  99, 100])

In [138]:
# 영어 성적 기준으로 각 열을 재정렬
c = np.argsort(a[1])
d = (a[0, c], a[1, c], a[2, c])
np.vstack(d)

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

### 7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 던져서 나오는 숫자의 평균을 구하시오.

In [84]:
a = np.random.randint(1, 6, 100)
print(a)
a.mean() # == np.mean(a)

[3 3 1 2 2 5 3 3 5 2 1 3 3 5 4 4 4 3 1 1 4 3 2 4 5 1 2 1 3 2 1 5 2 1 3 5 3
 1 4 3 4 2 1 1 5 4 5 2 5 4 5 2 1 5 5 1 4 4 3 4 1 4 2 3 3 4 2 5 5 5 3 1 2 2
 1 2 2 2 2 3 4 2 1 4 4 5 1 2 4 4 2 4 2 4 4 3 3 1 4 1]


2.93

### 8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.