In [1]:
import numpy as np

In [2]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
b = np.array([(1.5,2,3),(4,5,6)],dtype = float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [4]:
b.dtype

dtype('float64')

In [5]:
b.dtype.name

'float64'

In [6]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b.dtype

dtype('float64')

In [9]:
b.ndim

2

In [10]:
b.size

6

In [11]:
len(b)

2

In [12]:
b.shape

(2, 3)

In [13]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [ ]:
np.zeros()

In [1]:
import math
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
        
        This is the smallest integer >= x.
    
    comb(n, k, /)
        Number of ways to choose k items from n items without repetition and without order

In [2]:
a = 1
b = 2
print("1. 값도 다르고, 참조도 다른 경우")
print(f'a 값, 주소 : {a}, {hex(id(a))}')
print(f'b 값, 주소 : {b}, {hex(id(b))}')
print(f'a == b : {a == b}')
print(f'a is b : {a is b}')


1. 값도 다르고, 참조도 다른 경우
a 값, 주소 : 1, 0x7ff8ec9c2730
b 값, 주소 : 2, 0x7ff8ec9c2750
a == b : False
a is b : False


In [3]:
e = [1, 2, 3]
f = [1, 2, 3]
print("3. 값이 같고, 참조가 다른 경우")
print(f'e 값, 주소 : {e}, {hex(id(e))}')
print(f'f 값, 주소 : {f}, {hex(id(f))}')
print(f'e == f : {e == f}')
print(f'e is f : {e is f}')



3. 값이 같고, 참조가 다른 경우
e 값, 주소 : [1, 2, 3], 0x239185cf140
f 값, 주소 : [1, 2, 3], 0x239185cdc40
e == f : True
e is f : False


In [7]:
for i in range(5):
    print((i+1)*'*')

*
**
***
****
*****


In [26]:
for i in range(5):
    for k in range(i+1):
        print('*', end='')
    print()

*
**
***
****
*****


In [27]:
a = int(input())
for i in range(a):
    for k in range(a-i):
        print('*', end='')
    print()

*******
******
*****
****
***
**
*


In [40]:
for i in range(5,0,-1):
    print(i*'*')

*****
****
***
**
*


In [42]:
a = int(input())
for i in range(a,0,-1):
    print(i*'*')

********
*******
******
*****
****
***
**
*


In [7]:
import numpy as np

In [8]:
print(np.__version__)
np.show_config()

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ICT01_10/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ICT01_10/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ICT01_10/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ICT01_10/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ICT01_10/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ICT01_10/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ICT01_10/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ICT01_10/anaconda3\\Library\\include']


In [9]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
len(Z)

40

In [14]:
Z = np.arange(50)
Z = Z[::-1]
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [15]:
Z = np.arange(50)

In [16]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [18]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.99656347 0.55410585 0.84325942]
  [0.4969922  0.38872289 0.65463642]
  [0.66372067 0.92984475 0.12894043]]

 [[0.01172149 0.20810636 0.11209507]
  [0.43441427 0.17653682 0.997283  ]
  [0.54269194 0.77287408 0.74172809]]

 [[0.98193441 0.57720208 0.18469659]
  [0.12920533 0.99580076 0.21512328]
  [0.3733236  0.57452035 0.46458488]]]


In [20]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0034156274830974276 0.9989381361428032


In [21]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.4305735653028082


In [23]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [34]:
import math

In [35]:
b = math.nan
print(np.isnan(b))

True


In [36]:
print(np.nan)           # nan은 not a number 주어진 값이 유효하지 않음을 나타내는 상수
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)      # inf : infinitie
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
nan
False
False
nan
False


NULL은 존재하지 않고 비어있는 것

In [42]:
class MyClass:
    def myFunction(self):
        print('Hello')

# class1 = MyClass()
# class1.myFunction()
# del class1
# class1.myFunction()
# MyClass.myFunction()

AttributeError: 'str' object has no attribute 'MyClass'

In [45]:
print(id(MyClass))
print(id(MyClass.myFunction))

1858276456800
1858300392208


In [46]:
a = MyClass()
b = MyClass()

In [48]:
print(f'MyClass의 id : {id(MyClass)}, a의 id : {id(a)}, b의 id : {id(b)}')

MyClass의 id : 1858276456800, a의 id : 1858299493488, b의 id : 1858299492528


In [49]:
dir()

['In',
 'MyClass',
 'Out',
 'Z',
 'Zmax',
 'Zmin',
 '_',
 '_12',
 '_14',
 '_23',
 '_24',
 '_31',
 '_32',
 '_38',
 '_43',
 '_44',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i23',
 '_i24',
 '_i25',
 '_i26',
 '_i27',
 '_i28',
 '_i29',
 '_i3',
 '_i30',
 '_i31',
 '_i32',
 '_i33',
 '_i34',
 '_i35',
 '_i36',
 '_i37',
 '_i38',
 '_i39',
 '_i4',
 '_i40',
 '_i41',
 '_i42',
 '_i43',
 '_i44',
 '_i45',
 '_i46',
 '_i47',
 '_i48',
 '_i49',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'a',
 'b',
 'exit',
 'get_ipython',
 'i',
 'k',
 'm',
 'math',
 'np',
 'nz',
 'os',
 'quit',
 'sys']