In [1]:
import numpy as np

In [2]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
b = np.array([(1.5,2,3),(4,5,6)],dtype = float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [4]:
b.dtype

dtype('float64')

In [5]:
b.dtype.name

'float64'

In [6]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b.dtype

dtype('float64')

In [9]:
b.ndim

2

In [10]:
b.size

6

In [11]:
len(b)

2

In [12]:
b.shape

(2, 3)

In [13]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [ ]:
np.zeros()