In [1]:
import numpy as np

In [3]:
array1 = np.arange(10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
print('array1:\n', array1) # 아 문자열인데 착각함

array1:
 [0 1 2 3 4 5 6 7 8 9]


In [8]:
array2 = array1.reshape(2,5), 
array2

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),)

In [28]:
# array3 = array1.reshape(2,4) 처럼 지정된 사이즈로 변경 불가시 오류
array3 = array1.reshape(5, -1) # 양쪽 다 -1 지정하면 오류. 한쪽만 -1 쓰면 다른쪽 값에 맞춰서 바꾸라는 지시
array3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [15]:
# reshape(-1,1)과 같은 형태로 자주 사용. 반드시 1개의 칼럼(열)을 가진 ndarray로 변환.
# stack이나 concat으로 배열 결합시 ndarray 형태 통일

In [26]:
array3.tolist()

[[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]]

In [29]:
type(array3)

numpy.ndarray

In [20]:
# type() 은 데이터 타입 확인
# dtype() 은 ndarray의 데이터 타입 확인

In [35]:
array3.shape, array3.ndim, array3.dtype # 메서드 뒤에 괄호 안 붙음. 인수를 받을 필요가 없는 메서드

((5, 2), 2, dtype('int32'))

In [36]:
array6 = array1.reshape(-1,1)
array6 # 1 x 10 배열을 10 x 1 배열(2차원)로 바꿈

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## 인덱싱(indexing)
- 1. 특정한 데이터 추출(원하는 위치의 인덱스를 지정해서 해당 데이터를 반환)
- 2. 슬라이싱(연속된 ndarray 추출. 시작:종료-1)
- 3. 팬시 인덱싱(일정한 인덱싱 집합을 리스트나 ndarray 형태로 지정해서 그 위치의 데이터 반환)
- 4. 불린 인덱싱(조건에 따른 True/False를 판단해 true에 해당하는 인덱스 위치의 데이터 반환)

In [37]:
# 1차원
array1 = np.arange(start=1, stop=10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a = array1[2]
type(a), type(array1)

(numpy.int32, numpy.ndarray)

In [41]:
# 단일 인덱스로 ndarray 내의 데이터값 수정
array1[3] = 24
array1

array([ 1,  2,  3, 24,  5,  6,  7,  8,  9])

In [44]:
# 다차원
array1d = np.arange(1,10)
array2d = array1.reshape(3,3)
array2d

array([[ 1,  2,  3],
       [24,  5,  6],
       [ 7,  8,  9]])

In [46]:
array2d[0,0], array2d[2,1] # 행, 열(row, column) 순으로. 시작은 0부터
# axis = 0 열(세로), axis =1 행(가로)

(1, 8)

In [47]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [50]:
d[1, 0, 1]

12

In [51]:
# 슬라이싱 3차원
d[:1, 1:2, :]

array([[[5, 6, 7, 8]]])

In [52]:
d[1:, 2:, :2]

array([[[19, 20]]])

In [54]:
d[0, 2, 2:] # 한쪽에만 슬라이싱 적용하고 나머지 단일값 줘도 됨

array([11, 12])

In [58]:
d[:1, 2, 2:] # 위랑 비교. 슬라이싱을 몇 번 주냐에 따라 반환값 차원이 달라짐

array([[11, 12]])

In [57]:
d[1, 2]

array([19, 20, 21, 22])

In [ ]:
# 팬시 인덱싱
